### ISSUE TITLE
Can't get the plugin to work.

### ISSUE THREAD

**Issue by dickydick1963** [vniehues/homebridge-linak#6]
I installed on a clean pi4 under pi account
desk is paired
Idasen-controller is working
installed the plugin
configured as given.
Nothing is happening.

**Comment by vniehues** [comment]
Hey @dickydick1963 thank you for opening this issue.
That's sad to hear! Can you provide the logs from your homebridge, please?
Please check if homebridge can actually run the idasen-controller command with the following steps:

- log into your homebridge ui
- open a terminal window using the "three-dot-menu" at the top right
- run this simple command: `idasen-controller`

Please post the output of that command here

**Comment by dickydick1963** [comment]
Hello,

I found solution in closed issue. I had to install Idasen-controller under homebridge account. 
It works!
thx

**Comment by vniehues** [comment]
Thank you for the update! :)
I'll make a change in the readme since this seems to be a common issue.
