### ISSUE TITLE
Implement 'server mode'

### ISSUE THREAD

**Issue by gaborszello** [vniehues/homebridge-linak#8]
This has a number of use-cases, one of which is making the response time a lot quicker as the original creator of idasen-controller mentioned. I saw some WIP code in the development branch, would you like to release it in the near future?

**Comment by vniehues** [comment]
I don't think i will pick that branch back up anytime in the future.. 

For my use the latency is fine. The desk doesn't move very fast either way so the additional 1-3 seconds of wait time don't justify a rewrite of the connection logic.
